apiVersion: v1
kind: Service
metadata:
  name: mailbox-client-service
  labels:
    app: mailbox
spec:
  ports:
  - name: mailbox-port-443
    port: 443
  - name: mailbox-port-7071
    port: 7071
  clusterIP: None
  selector:
    app: mailbox
