apiVersion: v1
kind: Service
metadata:
  name: mailbox-service-external
  labels:
    app: mailbox
spec:
  ports:
  - name: mailbox-port-22
    port: 22
  - name: mailbox-port-25
    port: 25
  - name: mailbox-port-456
    port: 456
  - name: mailbox-port-587
    port: 587
  - name: mailbox-port-110
    port: 110
  - name: mailbox-port-143
    port: 143
  - name: mailbox-port-993
    port: 993
  - name: mailbox-port-995
    port: 995
  - name: mailbox-port-8080
    port: 8080
  - name: mailbox-port-8443
    port: 8443
  selector:
    app: mailbox
