apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 name: mailbox
spec:
 serviceName: mailbox-service
 replicas: 2
 template:
   metadata:
     labels:
       app: mailbox
   spec:
     containers:
     - name: mailbox
       image: 092658368226.dkr.ecr.us-east-1.amazonaws.com/synacor/zimbra-mailbox
       imagePullPolicy: Always
       volumeMounts:
       - name: zimbra-volume
         mountPath: /etc/config
       - name: mailbox-disk
         mountPath: /opt/zimbra
       env:
       - name: EXT_DOMAIN
         value: arvin-k8s.cascadeo.info
       - name: EXT_HOST
         value: zimbra
       - name: PASSWORD
         value: temp1234
       ports:
       - containerPort: 22
       - containerPort: 25
       - containerPort: 80
       - containerPort: 110
       - containerPort: 143
       - containerPort: 389
       - containerPort: 443
       - containerPort: 465
       - containerPort: 587
       - containerPort: 993
       - containerPort: 995
       - containerPort: 7071
       - containerPort: 8080
       - containerPort: 8443
     volumeClaimTemplates:
     - metadata:
         name: mailbox-disk
         annotations:
           volume.alpha.kubernetes.io/storage-class: anything
         spec:
           accessModes: [ "ReadWriteOnce" ]
           resources:
             requests:
               storage: 10Gi
     volumes:
     - name: zimbra-volume
       configMap:
         name: zimbra-mailbox
         items:
         - key: zimbra-properties
           path: zimbra.conf
     imagePullSecrets:
     - name: myregistrykey
