apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 name: ldap
spec:
 serviceName: ldap-service
 replicas: 1
 template:
   metadata:
     labels:
       app: ldap
   spec:
     containers:
     - name: ldap
       image: index.docker.io/cascadeo/zimbra-ldap
       imagePullPolicy: Always
       volumeMounts:
       - name: zimbra-volume
         mountPath: /etc/config
       env:
       - name: EXT_DOMAIN
         value: arvin-k8s.cascadeo.info
       - name: EXT_HOST
         value: zimbra
       - name: PASSWORD
         value: temp1234
       ports:
       - containerPort: 22
       - containerPort: 389
     volumes:
     - name: zimbra-volume
       configMap:
         name: zimbra-config
         items:
         - key: zimbra-properties
           path: zimbra.conf
     imagePullSecrets:
     - name: myregistrykey
