apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-s3-config
  labels:
    app: {{template "fullname" .}}
data:
  credentials: |
    [default]
    aws_access_key_id={{ .Values.s3.AccessKey }}
    aws_secret_access_key={{ .Values.s3.SecretKey }}
