kind: PersistentVolume
apiVersion: v1
metadata:
  name: mailbox-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: 
    fsType: ext4
