apiVersion: v1
kind: Service
metadata:
 name: proxy-service
spec:
 clusterIP: None
 ports:
   - name: zimbra-port-443
     port: 443
   - name: zimbra-port-110
     port: 110
   - name: zimbra-port-995
     port: 995
   - name: zimbra-port-143
     port: 143
   - name: zimbra-port-993
     port: 993
   - name: zimbra-port-7071
     port: 7071
   - name: zimbra-port-9071
     port: 9071
 selector:
   app: proxy
