apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 name: proxy-test
spec:
 serviceName: proxy-service-test
 replicas: 1
 template:
   metadata:
     labels:
       app: proxy-test
   spec:
     containers:
     - name: proxy-test
       image: index.docker.io/cascadeo/zimbra-proxy:v2
       imagePullPolicy: Always
       command: [ "/bin/sh", "-c", "cat /etc/zimbra.properties" ]
       volumeMounts:
       - name: zimbra-volume
         mountPath: /etc/
         subPath: zimbra.properties
       env:
       - name: EXT_DOMAIN
         value: arvin-k8s.cascadeo.info
       - name: EXT_HOST
         value: zimbra
       - name: PASSWORD
         value: temp1234
       ports:
       - containerPort: 22
       - containerPort: 25
       - containerPort: 80
       - containerPort: 110
       - containerPort: 143
       - containerPort: 389
       - containerPort: 443
       - containerPort: 465
       - containerPort: 587
       - containerPort: 993
       - containerPort: 995
       - containerPort: 7071
       - containerPort: 8080
       - containerPort: 8443
     volumes:
     - name: zimbra-volume
       configMap:
         name: zimbra-config
         items:
         - key: zimbra.properties
           path: zimbra.properties
     imagePullSecrets:
     - name: mysecret
